### ISSUE TITLE
Factor Out Common Distance API to Leverage `eval_op`, ... etc.

### ISSUE THREAD

**Issue by bhgomes** [JuliaStats/Distances.jl#126]
I think it would be beneficial to factor out the `eval_op`, `eval_end`, `eval_reduce` API so that others who want to define custom metrics (like #95) can extend the already optimized `evaluate` that is built off of them. Not sure how this would interact with `UnionMetrics`.

**Comment by dkarrasch** [comment]
@bhgomes Could it be that this is resolved by #163? Depending on what you want to define, `PreMetric`, `SemiMetric` or `Metric`, you can subtype your custom metric to `Union[Pre/Semi]Metric`, overload those functions that are not covered by the generic fallbacks, and otherwise let the package do its job. See https://github.com/JuliaStats/Distances.jl/issues/151#issuecomment-612460855 for an example.

**Comment by dkarrasch** [comment]
Closed by #163.
