### ISSUE TITLE
Incorrect estimation of the numeric type of the distance between Real elements: result is Int64, not Float64 or Real

### ISSUE THREAD

**Issue by aborzunov** [JuliaStats/Distances.jl#267]
Steps to reproduce:
```
julia> result_type(SqEuclidean(), Matrix{Real}(undef, 1, 1), Vector{Real}(undef, 1))
Int64
```

Julia: `Version 1.11.1 (2024-10-16)`
Distances: `[b4f34e82] Distances v0.10.12`

Issue originally was found during use of `Clustering.jl`: https://github.com/JuliaStats/Clustering.jl/issues/285

**Comment by dkarrasch** [comment]
In the OP, why is the data of generic type `Real`? This is not an issue with Distances.jl, this behaviour is deeply rooted in julia itself:

```julia
julia> typeof(one(Real))
Int64
```

This is because `one(::Type{T}) where {T<:Number} = convert(T,1)`. If you have floating point data anyway, it's better to use the most specific eltype possible. In your case, the elements of your arrays (in the OP) are all (but one) of type `Float64`. If, for some reason, you need to be more flexible, you could even use `AbstractFloat`:

```julia
julia> typeof(one(AbstractFloat))
Float64
```

or otherwise

```julia
convert(Array{Float64}, fs)
```
