### ISSUE TITLE
pairwise to work on rows instead of columns.

### ISSUE THREAD

**Issue by musm** [JuliaStats/Distances.jl#35]
Say I have a large matrix X in memory
I would like to use `pairwise` operating on the rows instead of the columns, without having to pass the transpose of X (so to not allocate another object in memory).

**Comment by rawls238** [comment]
I think this is a good idea, I'll put up an implementation of this unless @KristofferC has any objections about adding this

**Comment by musmo** [comment]
What would be a minimally invasive approach?

**Comment by nalimilan** [comment]
`transpose` now returns a lazy wrapper, so this may no longer be an issue.

OTOH it could be clearer for users to be able to specify the dimension over which variables are stored, since we differ from the convention used by other languages (see also https://github.com/JuliaStats/Clustering.jl/issues/79). Another reason is that `cov` supports such an argument (and expects variables to be stored by column by default...).

**Comment by nalimilan** [comment]
I've filed https://github.com/JuliaStats/Distances.jl/pull/121 taking advantage of `transpose` to support a `dims` argument. Please comment there.
